package com.zh.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.app.tvproject.mvp.model.data.ContentBean;

import com.zh.greendao.ContentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contentBeanDaoConfig;

    private final ContentBeanDao contentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contentBeanDaoConfig = daoConfigMap.get(ContentBeanDao.class).clone();
        contentBeanDaoConfig.initIdentityScope(type);

        contentBeanDao = new ContentBeanDao(contentBeanDaoConfig, this);

        registerDao(ContentBean.class, contentBeanDao);
    }
    
    public void clear() {
        contentBeanDaoConfig.clearIdentityScope();
    }

    public ContentBeanDao getContentBeanDao() {
        return contentBeanDao;
    }

}
